module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx,html}'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tertiary: 'var(--tertiary)',
        outline: 'var(--outline)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'error-container': 'var(--error-container)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        primary: 'var(--primary)',
        'surface-tint': 'var(--surface-tint)',
        'surface-container': 'var(--surface-container)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'on-primary-container': 'var(--on-primary-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'surface-dim': 'var(--surface-dim)',
        'inverse-primary': 'var(--inverse-primary)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'surface-bright': 'var(--surface-bright)',
        'on-error-container': 'var(--on-error-container)',
        error: 'var(--error)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-secondary': 'var(--on-secondary)',
        'outline-variant': 'var(--outline-variant)',
        'inverse-surface': 'var(--inverse-surface)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'surface-container-low': 'var(--surface-container-low)',
        'secondary-container': 'var(--secondary-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'on-primary': 'var(--on-primary)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'on-background': 'var(--on-background)',
        secondary: 'var(--secondary)',
        surface: 'var(--surface)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'surface-variant': 'var(--surface-variant)',
        'primary-container': 'var(--primary-container)',
        'on-error': 'var(--on-error)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'tertiary-container': 'var(--tertiary-container)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'primary-fixed': 'var(--primary-fixed)',
        background: 'var(--background)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'on-tertiary': 'var(--on-tertiary)',
        'on-surface': 'var(--on-surface)',
        'brand-green': 'var(--brand-green)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '32px',
        'sidebar-width': '280px',
        'inspector-width': '320px',
        gutter: '20px',
        base: '4px',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'mono-code': ['JetBrains Mono'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-caps': ['Inter'],
        'title-sm': ['Inter'],
        'display-lg': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'mono-code': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'title-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.03em', fontWeight: '800' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    // container queries plugin is experimental; install if needed
  ],
};
