const now = Date.now();
const daysAgo = (days) => new Date(now - days * 24 * 60 * 60 * 1000).toISOString();

export function createSeedAdminState() {
  return {
    overview: {
      totalUsers: 12842,
      activeUsers: 4210,
      documentsProcessed: 892440,
      mrr: 42105,
      apiHealth: 99.98,
      avgLatency: 1.2,
      growth: 12.5,
      docGrowth: 24,
    },
    users: [
      {
        id: "u-001",
        name: "Jane Doe",
        email: "jane@example.com",
        plan: "Enterprise AI",
        status: "Active",
        documents: 42,
        lastSeen: daysAgo(0.2),
        createdAt: daysAgo(120),
      },
      {
        id: "u-002",
        name: "Mark Smith",
        email: "mark@example.com",
        plan: "Pro Monthly",
        status: "Active",
        documents: 17,
        lastSeen: daysAgo(1.1),
        createdAt: daysAgo(34),
      },
      {
        id: "u-003",
        name: "Sam King",
        email: "sam@example.com",
        plan: "Enterprise Admin",
        status: "Suspended",
        documents: 88,
        lastSeen: daysAgo(6),
        createdAt: daysAgo(280),
      },
      {
        id: "u-004",
        name: "Ayesha Khan",
        email: "ayesha@example.com",
        plan: "Free Starter",
        status: "Active",
        documents: 5,
        lastSeen: daysAgo(0.7),
        createdAt: daysAgo(18),
      },
      {
        id: "u-005",
        name: "Omar Ali",
        email: "omar@example.com",
        plan: "Pro Monthly",
        status: "Pending",
        documents: 0,
        lastSeen: daysAgo(2),
        createdAt: daysAgo(4),
      },
    ],
    documents: [
      {
        id: "d-101",
        fileName: "Q3_Financial_Rpt.pdf",
        owner: "Jane Doe",
        status: "Ready",
        pages: 42,
        size: "8.2 MB",
        uploadedAt: daysAgo(1.2),
        risk: "Low",
      },
      {
        id: "d-102",
        fileName: "Market_Analysis.pdf",
        owner: "Mark Smith",
        status: "Processing",
        pages: 18,
        size: "4.1 MB",
        uploadedAt: daysAgo(0.7),
        risk: "Low",
      },
      {
        id: "d-103",
        fileName: "Annual_Audit_2023.pdf",
        owner: "Sam King",
        status: "Flagged",
        pages: 96,
        size: "14.6 MB",
        uploadedAt: daysAgo(2.4),
        risk: "High",
      },
      {
        id: "d-104",
        fileName: "Marketing_Playbook.pdf",
        owner: "Ayesha Khan",
        status: "Ready",
        pages: 28,
        size: "2.9 MB",
        uploadedAt: daysAgo(0.1),
        risk: "Medium",
      },
    ],
    subscriptions: {
      plans: [
        { name: "Enterprise AI", value: 42, color: "bg-primary" },
        { name: "Pro Monthly", value: 38, color: "bg-blue-500" },
        { name: "Free Starter", value: 20, color: "bg-orange-400" },
      ],
      invoices: [
        { id: "inv-1001", customer: "Jane Doe", amount: "$499", status: "Paid", date: daysAgo(3) },
        { id: "inv-1002", customer: "Mark Smith", amount: "$49", status: "Due", date: daysAgo(5) },
        { id: "inv-1003", customer: "Ayesha Khan", amount: "$0", status: "Trial", date: daysAgo(1) },
      ],
    },
    settings: {
      portalName: "Lumina AI",
      maintenanceMode: false,
      guestUploadsEnabled: true,
      autoPurgeDays: 30,
      apiRateLimit: 120,
      modelName: "Gemini 2.5 Flash",
      encryption: "AES-256",
      auditRetentionDays: 90,
    },
    api: {
      clusterStatus: "Live Cluster",
      processingCore: "GPU (Metal/CUDA)",
      health: [
        { name: "Auth API", status: "Healthy", latency: "1.1ms" },
        { name: "Upload Pipeline", status: "Healthy", latency: "2.4s avg" },
        { name: "Chat Engine", status: "Degraded", latency: "380ms" },
        { name: "Export Service", status: "Healthy", latency: "0.8ms" },
      ],
      endpoints: [
        { path: "/api/auth/login", requests: 18244, errors: 2 },
        { path: "/api/upload", requests: 8421, errors: 11 },
        { path: "/api/chat/:id", requests: 44211, errors: 17 },
        { path: "/api/documents", requests: 90211, errors: 4 },
      ],
    },
    activity: [
      { id: "a-1", user: "Jane Doe", action: "Summarized PDF", target: "Q3_Financial_Rpt.pdf", time: "2 mins ago", status: "Success" },
      { id: "a-2", user: "Mark Smith", action: "File Upload", target: "Market_Analysis.pdf", time: "14 mins ago", status: "Success" },
      { id: "a-3", user: "Sam King", action: "Bulk Export", target: "Annual_Audit_2023.zip", time: "1 hour ago", status: "Failed" },
    ],
    audit: [
      { id: "l-1", actor: "Admin User", event: "Updated API rate limit to 120", severity: "Info", time: daysAgo(0.3) },
      { id: "l-2", actor: "System", event: "Chat engine latency elevated", severity: "Warning", time: daysAgo(0.4) },
      { id: "l-3", actor: "Jane Doe", event: "Downloaded summary export", severity: "Info", time: daysAgo(0.8) },
      { id: "l-4", actor: "Sam King", event: "Suspicious bulk export blocked", severity: "High", time: daysAgo(1.1) },
    ],
  };
}
